### PR TITLE
Finally fix ip error on installation

### PR DESCRIPTION
**Pull request by SkyWarZzeur**
Fix by @MrMicky-FR, need testing.

### CODE REVIEW

**Comment by MaximeMichaud** [comment]
Si personne ne teste, je vais m'en charger.
Sauf, si quelqu'un souhaite testé, qu'il le fasse, car, moi ce ne sera pas dans l'immédiat.

**Comment by Eywek** [comment]
Duplicated #184

**Comment by MrMicky-FR** [comment]
@Eywek This PR was opened first but is marked as duplicate ? I don’t really care but don’t seems logical..

**Comment by Eywek** [comment]
Checks were failing sorry

**Pull request closed without merging**
